eureka:
  client:
    service-url:
        defaultZone : http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost

microservice:
 payment-service:
  endpoints:
    endpoint:
      uri : http://PAYMENT-SERVICE/payment/doPayement
 ordre-service:
  endpoints:
    endpoint:
      uri :  http://ORDER-SERVICE/order/bookOrder
